use crate::models::request::{
    AccessionPagination, AccessionPaginationWithPrivate, AuthorizeRequest, CollectionLangParam,
    CollectionPagination, CollectionPaginationWithPrivate, ContributorLangParam,
    ContributorPagination, ContributorRoleLangParam, ContributorRolePagination,
    CreateAccessionRequest, CreateAccessionRequestRaw, CreateCollectionRequest,
    CreateContributorRequest, CreateContributorRoleRequest, CreateCreatorRequest,
    CreateLocationRequest, CreateRelationRequest, CreateSubjectRequest, CreateUserRequest,
    CreatorLangParam, CreatorPagination, DeleteContributorRequest, DeleteContributorRoleRequest,
    DeleteCreatorRequest, DeleteLocationRequest, DeleteSubjectRequest, LocationLangParam,
    LocationPagination, LoginRequest, RelationLangParam, RevokeApiKeyRequest, SubjectLangParam,
    SubjectPagination, UpdateAccessionRequest, UpdateCollectionRequest, UpdateContributorRequest,
    UpdateContributorRoleRequest, UpdateCreatorRequest, UpdateLocationRequest,
    UpdateSubjectRequest, UpdateUserRequest, UserPagination,
};
use crate::models::response::{
    CollectionResponse, ContributorResponse, ContributorRoleResponse, CreateApiKeyResponse,
    CreatorResponse, GetOneAccessionResponse, ListAccessionsResponse, ListCollectionsResponse,
    ListContributorRolesArResponse, ListContributorRolesEnResponse, ListContributorsArResponse,
    ListContributorsEnResponse, ListCreatorsResponse, ListLocationsResponse,
    ListSubjectsArResponse, ListSubjectsEnResponse, ListUsersResponse, LocationResponse,
    RelationResponse, SubjectResponse, UserResponse,
};
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa::{Modify, OpenApi};
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.as_mut().unwrap();
        components.add_security_scheme(
            "jwt_cookie_auth",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("jwt"))),
        );
        components.add_security_scheme(
            "api_key_auth",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-Api-Key"))),
        );
    }
}

/// OpenAPI specification for the Sudan Digital Archive API
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::health::healthcheck,
        crate::routes::accessions::create_accession_crawl,
        crate::routes::accessions::create_accession_raw,
        crate::routes::accessions::get_one_accession,
        crate::routes::accessions::get_one_private_accession,
        crate::routes::accessions::list_accessions,
        crate::routes::accessions::list_accessions_private,
        crate::routes::accessions::delete_accession,
        crate::routes::accessions::update_accession,
        crate::routes::auth::login,
        crate::routes::auth::authorize,
        crate::routes::auth::verify,
        crate::routes::auth::create_api_key,
        crate::routes::auth::revoke_api_key,
        crate::routes::auth::create_user,
        crate::routes::auth::list_users,
        crate::routes::auth::get_user,
        crate::routes::auth::update_user,
        crate::routes::auth::delete_user,
        crate::routes::subjects::create_subject,
        crate::routes::subjects::list_subjects,
        crate::routes::subjects::get_one_subject,
        crate::routes::subjects::delete_subject,
        crate::routes::subjects::update_subject,
        crate::routes::locations::create_location,
        crate::routes::locations::list_locations,
        crate::routes::locations::get_one_location,
        crate::routes::locations::delete_location,
        crate::routes::locations::update_location,
        crate::routes::creators::create_creator,
        crate::routes::creators::list_creators,
        crate::routes::creators::get_one_creator,
        crate::routes::creators::delete_creator,
        crate::routes::creators::update_creator,
        crate::routes::contributors::create_contributor,
        crate::routes::contributors::list_contributors,
        crate::routes::contributors::get_one_contributor,
        crate::routes::contributors::delete_contributor,
        crate::routes::contributors::update_contributor,
        crate::routes::contributors::create_role,
        crate::routes::contributors::list_roles,
        crate::routes::contributors::get_one_role,
        crate::routes::contributors::delete_role,
        crate::routes::contributors::update_role,
        crate::routes::collections::list_collections,
        crate::routes::collections::list_collections_private,
        crate::routes::collections::get_one_collection,
        crate::routes::collections::create_collection,
        crate::routes::collections::update_collection,
        crate::routes::collections::delete_collection,
        crate::routes::relations::create_relation,
        crate::routes::relations::list_relations,
        crate::routes::relations::get_one_relation,
        crate::routes::relations::delete_relation
    ),
    components(
        schemas(
            AccessionPagination,
            AccessionPaginationWithPrivate,
            CreateAccessionRequest,
            CreateAccessionRequestRaw,
            UpdateAccessionRequest,
            GetOneAccessionResponse,
            ListAccessionsResponse,
            LoginRequest,
            AuthorizeRequest,
            CreateApiKeyResponse,
            CreateSubjectRequest,
            UpdateSubjectRequest,
            DeleteSubjectRequest,
            SubjectPagination,
            SubjectLangParam,
            SubjectResponse,
            ListSubjectsEnResponse,
            ListSubjectsArResponse,
            CreateLocationRequest,
            UpdateLocationRequest,
            DeleteLocationRequest,
            LocationPagination,
            LocationLangParam,
            LocationResponse,
            ListLocationsResponse,
            CreateCreatorRequest,
            UpdateCreatorRequest,
            DeleteCreatorRequest,
            CreatorPagination,
            CreatorLangParam,
            CreatorResponse,
            ListCreatorsResponse,
            CreateContributorRequest,
            UpdateContributorRequest,
            DeleteContributorRequest,
            ContributorPagination,
            ContributorLangParam,
            ContributorResponse,
            ListContributorsEnResponse,
            ListContributorsArResponse,
            CreateContributorRoleRequest,
            UpdateContributorRoleRequest,
            DeleteContributorRoleRequest,
            ContributorRolePagination,
            ContributorRoleLangParam,
            ContributorRoleResponse,
            ListContributorRolesEnResponse,
            ListContributorRolesArResponse,
            CreateUserRequest,
            UpdateUserRequest,
            UserPagination,
            UserResponse,
            ListUsersResponse,
            RevokeApiKeyRequest,
            CollectionPagination,
            CollectionPaginationWithPrivate,
            CollectionLangParam,
            CreateCollectionRequest,
            UpdateCollectionRequest,
            CollectionResponse,
            ListCollectionsResponse,
            CreateRelationRequest,
            RelationLangParam,
            RelationResponse
        )
    ),
    tags(
        (name = "Healthcheck", description = "Health check endpoints"),
        (name = "Accessions", description = "Accession management endpoints"),
        (name = "Auth", description = "User authentication endpoints"),
        (name = "Subjects", description = "Dublin Metadata Subject management endpoints"),
        (name = "Locations", description = "Dublin Metadata Location management endpoints"),
        (name = "Creators", description = "Dublin Metadata Creator management endpoints"),
        (name = "Contributors", description = "Dublin Metadata Contributor and role management endpoints"),
        (name = "Collections", description = "Collection management endpoints"),
        (name = "Relations", description = "Dublin Metadata Relation management endpoints")
    ),
    modifiers(&SecurityAddon),
    servers(
        // Deployed on Digital Ocean spaces which has a HTTP request config that slaps on this sda-api prefix
        (url = "/sda-api", description = "Production deployment with prefix"),
        (url = "/", description = "Local development without prefix")
    )
)]
pub struct ApiDoc;
