//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collection_en")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub is_private: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_en_subjects::Entity")]
    CollectionEnSubjects,
}

impl Related<super::collection_en_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionEnSubjects.def()
    }
}

impl Related<super::dublin_metadata_subject_en::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_en_subjects::Relation::DublinMetadataSubjectEn.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::collection_en_subjects::Relation::CollectionEn
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
