//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::DublinMetadataRelationType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dublin_metadata_relation_en")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub relation_type: DublinMetadataRelationType,
    pub related_accession_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dublin_metadata_en_relations::Entity")]
    DublinMetadataEnRelations,
}

impl Related<super::dublin_metadata_en_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataEnRelations.def()
    }
}

impl Related<super::dublin_metadata_en::Entity> for Entity {
    fn to() -> RelationDef {
        super::dublin_metadata_en_relations::Relation::DublinMetadataEn.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::dublin_metadata_en_relations::Relation::DublinMetadataRelationEn
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
