//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dublin_metadata_subject_en")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub subject: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_en_subjects::Entity")]
    CollectionEnSubjects,
    #[sea_orm(has_many = "super::dublin_metadata_en_subjects::Entity")]
    DublinMetadataEnSubjects,
}

impl Related<super::collection_en_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionEnSubjects.def()
    }
}

impl Related<super::dublin_metadata_en_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataEnSubjects.def()
    }
}

impl Related<super::collection_en::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_en_subjects::Relation::CollectionEn.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::collection_en_subjects::Relation::DublinMetadataSubjectEn
                .def()
                .rev(),
        )
    }
}

impl Related<super::dublin_metadata_en::Entity> for Entity {
    fn to() -> RelationDef {
        super::dublin_metadata_en_subjects::Relation::DublinMetadataEn.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::dublin_metadata_en_subjects::Relation::DublinMetadataSubjectEn
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
