//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "dublin_metadata_en_contributors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub metadata_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub contributor_id: i32,
    pub role_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dublin_metadata_en::Entity",
        from = "Column::MetadataId",
        to = "super::dublin_metadata_en::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DublinMetadataEn,
    #[sea_orm(
        belongs_to = "super::dublin_metadata_contributor_en::Entity",
        from = "Column::ContributorId",
        to = "super::dublin_metadata_contributor_en::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DublinMetadataContributorEn,
    #[sea_orm(
        belongs_to = "super::dublin_metadata_contributor_role_en::Entity",
        from = "Column::RoleId",
        to = "super::dublin_metadata_contributor_role_en::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DublinMetadataContributorRoleEn,
}

impl Related<super::dublin_metadata_en::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataEn.def()
    }
}

impl Related<super::dublin_metadata_contributor_en::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataContributorEn.def()
    }
}

impl Related<super::dublin_metadata_contributor_role_en::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataContributorRoleEn.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
