//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dublin_metadata_ar")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub location_ar_id: Option<i32>,
    pub creator_ar_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accession::Entity")]
    Accession,
    #[sea_orm(has_many = "super::dublin_metadata_ar_contributors::Entity")]
    DublinMetadataArContributors,
    #[sea_orm(has_many = "super::dublin_metadata_ar_relations::Entity")]
    DublinMetadataArRelations,
    #[sea_orm(has_many = "super::dublin_metadata_ar_subjects::Entity")]
    DublinMetadataArSubjects,
    #[sea_orm(
        belongs_to = "super::dublin_metadata_creator_ar::Entity",
        from = "Column::CreatorArId",
        to = "super::dublin_metadata_creator_ar::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DublinMetadataCreatorAr,
    #[sea_orm(
        belongs_to = "super::dublin_metadata_location_ar::Entity",
        from = "Column::LocationArId",
        to = "super::dublin_metadata_location_ar::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DublinMetadataLocationAr,
}

impl Related<super::accession::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accession.def()
    }
}

impl Related<super::dublin_metadata_ar_contributors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataArContributors.def()
    }
}

impl Related<super::dublin_metadata_ar_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataArRelations.def()
    }
}

impl Related<super::dublin_metadata_ar_subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataArSubjects.def()
    }
}

impl Related<super::dublin_metadata_creator_ar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataCreatorAr.def()
    }
}

impl Related<super::dublin_metadata_location_ar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataLocationAr.def()
    }
}

impl Related<super::dublin_metadata_relation_ar::Entity> for Entity {
    fn to() -> RelationDef {
        super::dublin_metadata_ar_relations::Relation::DublinMetadataRelationAr.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::dublin_metadata_ar_relations::Relation::DublinMetadataAr
                .def()
                .rev(),
        )
    }
}

impl Related<super::dublin_metadata_subject_ar::Entity> for Entity {
    fn to() -> RelationDef {
        super::dublin_metadata_ar_subjects::Relation::DublinMetadataSubjectAr.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::dublin_metadata_ar_subjects::Relation::DublinMetadataAr
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
