//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "dublin_metadata_contributor_ar")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub contributor: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dublin_metadata_ar_contributors::Entity")]
    DublinMetadataArContributors,
}

impl Related<super::dublin_metadata_ar_contributors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataArContributors.def()
    }
}

impl Related<super::dublin_metadata_ar::Entity> for Entity {
    fn to() -> RelationDef {
        super::dublin_metadata_ar_contributors::Relation::DublinMetadataAr.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::dublin_metadata_ar_contributors::Relation::DublinMetadataContributorAr
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
