//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dublin_metadata_en_relations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub metadata_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub relation_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dublin_metadata_en::Entity",
        from = "Column::MetadataId",
        to = "super::dublin_metadata_en::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DublinMetadataEn,
    #[sea_orm(
        belongs_to = "super::dublin_metadata_relation_en::Entity",
        from = "Column::RelationId",
        to = "super::dublin_metadata_relation_en::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DublinMetadataRelationEn,
}

impl Related<super::dublin_metadata_en::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataEn.def()
    }
}

impl Related<super::dublin_metadata_relation_en::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataRelationEn.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
