//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dublin_metadata_contributor_en")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub contributor: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dublin_metadata_en_contributors::Entity")]
    DublinMetadataEnContributors,
}

impl Related<super::dublin_metadata_en_contributors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DublinMetadataEnContributors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
