//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "crawl_status")]
pub enum CrawlStatus {
    #[sea_orm(string_value = "bad_crawl")]
    BadCrawl,
    #[sea_orm(string_value = "complete")]
    Complete,
    #[sea_orm(string_value = "error")]
    Error,
    #[sea_orm(string_value = "pending")]
    Pending,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "dublin_metadata_format"
)]
pub enum DublinMetadataFormat {
    #[sea_orm(string_value = "wacz")]
    #[serde(rename = "wacz")]
    #[schema(rename = "wacz")]
    Wacz,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "admin")]
    #[serde(rename = "admin")]
    #[schema(rename = "admin")]
    Admin,
    #[sea_orm(string_value = "researcher")]
    #[serde(rename = "researcher")]
    #[schema(rename = "researcher")]
    Researcher,
    #[sea_orm(string_value = "contributor")]
    #[serde(rename = "contributor")]
    #[schema(rename = "contributor")]
    Contributor,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "dublin_metadata_relation_type"
)]
pub enum DublinMetadataRelationType {
    #[sea_orm(string_value = "has_part")]
    #[serde(rename = "has_part")]
    HasPart,
    #[sea_orm(string_value = "is_part_of")]
    #[serde(rename = "is_part_of")]
    IsPartOf,
    #[sea_orm(string_value = "has_version")]
    #[serde(rename = "has_version")]
    HasVersion,
    #[sea_orm(string_value = "is_version_of")]
    #[serde(rename = "is_version_of")]
    IsVersionOf,
    #[sea_orm(string_value = "references")]
    #[serde(rename = "references")]
    References,
    #[sea_orm(string_value = "is_referenced_by")]
    #[serde(rename = "is_referenced_by")]
    IsReferencedBy,
    #[sea_orm(string_value = "conforms_to")]
    #[serde(rename = "conforms_to")]
    ConformsTo,
    #[sea_orm(string_value = "requires")]
    #[serde(rename = "requires")]
    Requires,
}
